# Generated by Django 4.0.5 on 2022-06-28 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='beltApp.user'),
        ),
    ]
